<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from /Users/monish/src/civi-extensions/biz.jmaconsulting.freeeventtemplate/xml/schema/CRM/Freeeventtemplate/FreeEvent.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:d606f1649db336b5f7eae643508c1243)
 */

/**
 * Database access object for the FreeEvent entity.
 */
class CRM_Freeeventtemplate_DAO_FreeEvent extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_free_event';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique FreeEvent ID
   *
   * @var int
   */
  public $id;

  /**
   * FK to Event
   *
   * @var int
   */
  public $event_id;

  /**
   * Is Free Event?
   *
   * @var int
   */
  public $free_event;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_free_event';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   */
  public static function getEntityTitle() {
    return ts('Free Events');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'event_id', 'civicrm_event', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => ts('Unique FreeEvent ID'),
          'required' => TRUE,
          'where' => 'civicrm_free_event.id',
          'table_name' => 'civicrm_free_event',
          'entity' => 'FreeEvent',
          'bao' => 'CRM_Freeeventtemplate_DAO_FreeEvent',
          'localizable' => 0,
        ],
        'event_id' => [
          'name' => 'event_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => ts('FK to Event'),
          'where' => 'civicrm_free_event.event_id',
          'table_name' => 'civicrm_free_event',
          'entity' => 'FreeEvent',
          'bao' => 'CRM_Freeeventtemplate_DAO_FreeEvent',
          'localizable' => 0,
        ],
        'free_event' => [
          'name' => 'free_event',
          'type' => CRM_Utils_Type::T_INT,
          'title' => ts('Free Event'),
          'description' => ts('Is Free Event?'),
          'where' => 'civicrm_free_event.free_event',
          'default' => '0',
          'table_name' => 'civicrm_free_event',
          'entity' => 'FreeEvent',
          'bao' => 'CRM_Freeeventtemplate_DAO_FreeEvent',
          'localizable' => 0,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'free_event', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'free_event', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
